// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRzEkszOyUR9PQ369lniU9TgNelqrSz4A',
    appId: '1:268039661382:web:c9803519291dff43f3a747',
    messagingSenderId: '268039661382',
    projectId: 'my-ceyiz-takip',
    authDomain: 'my-ceyiz-takip.firebaseapp.com',
    storageBucket: 'my-ceyiz-takip.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOt6NPHp6TXcsRCdUGoSC6Hj5vkjnw0eI',
    appId: '1:268039661382:android:52e90454ad099aa7f3a747',
    messagingSenderId: '268039661382',
    projectId: 'my-ceyiz-takip',
    storageBucket: 'my-ceyiz-takip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZx2KngTFQ-A4iSW4bD_lbuWgdu8LpyrI',
    appId: '1:268039661382:ios:16d5a72ee6f8805df3a747',
    messagingSenderId: '268039661382',
    projectId: 'my-ceyiz-takip',
    storageBucket: 'my-ceyiz-takip.firebasestorage.app',
    iosBundleId: 'com.example.flutterStartupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZx2KngTFQ-A4iSW4bD_lbuWgdu8LpyrI',
    appId: '1:268039661382:ios:16d5a72ee6f8805df3a747',
    messagingSenderId: '268039661382',
    projectId: 'my-ceyiz-takip',
    storageBucket: 'my-ceyiz-takip.firebasestorage.app',
    iosBundleId: 'com.example.flutterStartupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRzEkszOyUR9PQ369lniU9TgNelqrSz4A',
    appId: '1:268039661382:web:a2a19ae1839a9ca7f3a747',
    messagingSenderId: '268039661382',
    projectId: 'my-ceyiz-takip',
    authDomain: 'my-ceyiz-takip.firebaseapp.com',
    storageBucket: 'my-ceyiz-takip.firebasestorage.app',
  );
}
